### ISSUE TITLE
soundcloudを何曲かキューに入れると再生がスキップされる

### ISSUE THREAD

**Issue by SehataKuro** [Giratina-net/Giratina#161]
![image](https://user-images.githubusercontent.com/75165625/216040358-065793c5-5336-4334-a617-e39e35baf13d.png)
セッションがタイムアウトしているのではないでしょうか？よくわからないです

**Comment by naari3** [comment]
セッションというより、払い出されるURLの署名が切れてるんだと思います。

このffmpegのログを見るに、ffmpegが再生時に使っているURLはAWSのS3経由で払い出された「制限時間付き署名付きURL」にみえます。
挙動として、urlからYTDLSourceのオブジェクトを作成した段階でこの署名付きURLが生成され、そのままキューに積まれて再生の順番を待つ、という流れになります。
しかし、既にキューにたくさん曲が積まれている場合、この曲にたどり着いた段階でffmpegに渡される制限時間付き署名付きURLが寿命を迎えてしまうので再生できない、という感じにみえました。

**Comment by naari3** [comment]
事前にYTDLSourceを生成する理由はおそらくキューを表示させる際にタイトルを取得したいためですかね？そう見えます

**Comment by naari3** [comment]
かんたんな解決策は再生直前にYTDLSourceを再度作成する、くらいかなあ

**Comment by naari3** [comment]
やった
56ab10989debe9c7acec41472b475e90997eaf37
