### ISSUE TITLE
Actionsでの自動整形

### ISSUE THREAD

**Issue by Siwo951** [Giratina-net/Giratina#162]
- IDEに書式やimportで警告が付けられてる部分がたまにあるのでそれを無くす
- いろんなユーザーが書いても書式が統一される

上記2個を思いつき発案
やるとなったら[この記事](https://zenn.dev/satto_sann/articles/36c68c73dc5125)を参考にやるつもり

pushされてきたコードに影響を与える可能性のある変更なので一応意見があれば募りたいと思い立てました
特に無さそうなら一度実装して様子見します

**Comment by naari3** [comment]
- これを適用するには原則としてmasterブランチへのpushを辞める必要がありそう
  - そうでないと結局無意味になりそう
  - それかmasterブランチに対しても同等のことをする？CIにmasterへの直pushを許すかどうか
- 上記の前提がある場合、このプロジェクトへの参加者に「そもそもPRを作れること」という前提を課すことになりそう

なのでその点はどうなんだろうなと思いました

**Comment by naari3** [comment]
もしCIでこれをするなら、手元でも同じルールのもとフォーマッターが実行できるようにしたいですねー

個人的にはVSCodeを使っているんですが、フォーマッターに関する設定をリポジトリに含めておくとみんなが個別で設定する必要がなくなって良いかなと思っています

**Comment by Siwo951** [comment]
今の状態だとすぐそれとは出来なさそうですね ちょっと様子見します

**Comment by naari3** [comment]
@Siwo951 コードオーナーらしき人物である @SehataKuro さんに聞いたら「良いと思います」って言ってたので問題なさそうです！！

**Comment by naari3** [comment]
@Siwo951 masterブランチにプロテクトのルールを入れたんですが、もし不都合あったら教えてください

GitHub Actions の設定とかはこのリポジトリに直接生やしたブランチからのPRであればもんだいないかなと思っています

**Comment by Siwo951** [comment]
ちょっと期間空きましたが実装しました
